### ISSUE TITLE
Create database migrations for Content Types

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/owl-curriculum#23]

**Comment by KeynesYouDigIt** [comment]
Where is the to an from for these migrations? is the idea to go from dev to prod?

**Comment by dviramontes** [comment]
This is the library we are using to run migrations: https://github.com/yogthos/migratus
the owlet-cms is already setup for this though, we should be able to create the migrations
in `resources/migrations` directory. More than willing to pair up on this if you need help
