### ISSUE TITLE
Create user personas

### ISSUE THREAD

**Issue by eemshi** [codefordenver/owl-curriculum#33]

**Comment by rocioalmangui** [comment]
@dviramontes @eemshi [Owlet Personas EIleen.pdf](https://github.com/codefordenver/owl-curriculum/files/207724/Owlet.Personas.EIleen.pdf)
Do you think this gives you enough context to guide the design? Can you cc Dave in this thread to see what he thinks?

**Comment by eemshi** [comment]
Just added dave to the waffle @D3s1gnerUX

**Comment by rocioalmangui** [comment]
@eemshi does this person reflects your issues? Could it be useful if we print? [Megan Persona.pdf](https://github.com/codefordenver/owl-curriculum/files/209559/Megan.Persona.pdf)

**Comment by eemshi** [comment]
@rocioalmangui yes, exactly!

**Comment by rocioalmangui** [comment]
@eemshi please let me know if this reflects the issues your expert students go through, and if there are some other things TTIA could help them with. 
[Owlet Personas Frankie.pdf](https://github.com/codefordenver/owl-curriculum/files/219665/Owlet.Personas.Frankie.pdf)
